export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FETCH_PRODUCTS:"FETCH_PRODUCTS",

  POST_CART : "POST_CART",

  //cartRedux...
  ADD_CART : "ADD_CART",
  INC_PRICE_QUANTITY:"INC_PRICE_QUANTITY",
  DELETE_CART:"DELETE_CART",
  TOTAL_PRICE:"TOTAL_PRICE",
  TOTAL_ITEMS:"TOTAL_ITEMS",
  TOTAL_DISCOUNT:"TOTAL_DISCOUNT",
};
